name: paxa_print
description: Successor of Fiscalberry.
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=2.19.2 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    esc_pos_utils: ^1.1.0
    flutter_background: ^1.2.0
    uuid: ^3.0.7
    image: ^3.3.0
    hive: ^2.2.3
    hive_flutter: ^1.1.0
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/icons/
